server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway